services:
  user:
    container_name: user-service
    build:
      context: ./user
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - 3001:3001
    volumes:
      - ./user:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres-user
    networks:
      - microservices-net

  order:
    container_name: order-service
    build:
      context: ./order
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - 3002:3002
    volumes:
      - ./order:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres-order
    networks:
      - microservices-net

  search:
    container_name: search-service
    build:
      context: ./search
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - 3003:3003
    volumes:
      - ./search:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres-search
    networks:
      - microservices-net
  
  product:
    container_name: product-service
    build:
      context: ./product
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - 3004:3004
    volumes:
      - ./product:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres-product
    networks:
      - microservices-net

  postgres-user:
    image: postgres:16-alpine
    container_name: postgres-user
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
      PGDATA: /var/lib/postgresql/data/pgdata 
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - microservices-net
  
  postgres-order:
    image: postgres:16-alpine
    container_name: postgres-order
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-order-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - microservices-net



  postgres-product:
    image: postgres:16-alpine
    container_name: postgres-product
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-product-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - microservices-net

  postgres-search:
    image: postgres:16-alpine
    container_name: postgres-search
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: search
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-search-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - microservices-net
volumes:
  postgres-user-data:
  postgres-order-data:
  postgres-product-data:
  postgres-search-data:
networks:
  microservices-net:
    driver: bridge